### ISSUE TITLE
Bump to current version of Angelscript (2.33.0) from original repository

### ISSUE THREAD

**Issue by noizex** [hunter-packages/AngelScript#1]
Currently we have a very outdated (several years) version of Angelscript that seems to originate from Urho3D fork with some changes. This means this package and original library is now few years apart and is using different CMakeLists (one comes from Urho3D, other from original repo). I'd like to start some discussion around updating the version to current one and using original CMakeLists which have different conditions - right now Hunter's package won't compile in x64 by default (it needs URHO3D flag, which is not needed by original lib) and also it misses a lot of new additions - some of the main classes are not present in this source.

Source of recent version: https://www.angelcode.com/angelscript/downloads.html
Main repository (SVN): http://svn.code.sf.net/p/angelscript/code/trunk/
GitHub mirror (automatically updated): https://github.com/codecat/angelscript-mirror

Main CMakeLists file for the project: https://github.com/codecat/angelscript-mirror/blob/master/sdk/angelscript/projects/cmake/CMakeLists.txt

**Comment by ruslo** [comment]
I've created the `hunter-2.33.0` branch based on this commit:
- https://github.com/codecat/angelscript-mirror/commit/54bbe580c21b4a80f2aceb4cb81a04b9d8e80b3d

See:
- https://github.com/hunter-packages/AngelScript/tree/hunter-2.33.0

**Comment by noizex** [comment]
What would be the configuration for this package, since the CMakeLists is hidden within subdirectory and probably won't be visible to Hunter when compiling?

**Comment by ruslo** [comment]
Two choices here:
- Design and implement this feature: https://github.com/ruslo/hunter/issues/679
- Add top-level CMakeLists.txt to this fork

**Comment by noizex** [comment]
@ruslo how can I add this - right now I have no way to submit PR to this repo... I'd try first with top-level CMakeLists.txt since we already use a fork here, though that feature seems helpful, and I will have a look once I understand more how Hunter works internally

unless I'm supposed to fork it then PR from fork?

**Comment by ruslo** [comment]
> unless I'm supposed to fork it then PR from fork?

Yes, that's the regular GitHub workflow. You fork the project you want to send pull request to, then push to your branch, then open pull request.

**Comment by noizex** [comment]
Managed to get fork to compile (using top-level CMakeLists that just includes the nested one), but when running local tests with my fork being the source I get this when compiling the example/Angelscript project:
```
CMake Error at CMakeLists.txt:15 (add_executable):
  Target "boo" links to target "Threads::Threads" but the target was not
  found.  Perhaps a find_package() call is missing for an IMPORTED target, or
  an ALIAS target is missing?
```
It seems both CMakeLists (old one and original) pull Thread::Thread in similar way so not sure what else is done to guarantee that Threads are found during the run of example. 

I attached cmake/Angelscript output from Install directory.
[Angelscript.zip](https://github.com/hunter-packages/AngelScript/files/3104007/Angelscript.zip)

Might be it only does find_package when compiling Angelscript, but it doesn't do it when it's being compiled as a part of the project that uses it as dependency? I see that version 2.30 has this directory:
https://github.com/hunter-packages/AngelScript/blob/hunter-2.30/cmake/Config.cmake.in
that seems to do something, but not sure what. Am I supposed to provide it in 2.33.0 too?

**Comment by noizex** [comment]
And if so, how do I do this, because it seems the old version did INSTALL commands in its own way, and here we're "reusing" original CMakeLists that already does some installs. They just don't seem to be compatible with Hunter's way of installing/finding packages so it breaks on Threads::Threads not found - if I understand this correctly.

**Comment by ruslo** [comment]
> Am I supposed to provide it in 2.33.0 too?

Yes, I think it's a problem, missing part:
- https://github.com/hunter-packages/AngelScript/blob/v2.30-p0/cmake/Config.cmake.in#L3

**Comment by ruslo** [comment]
It will be easier to do a review if you open pull request with the code you're testing.

**Comment by noizex** [comment]
I will try to patch original CMakeLists then, it already copies some very basic config, I'll just add the same exact config it used in 2.30 and post a PR

**Comment by noizex** [comment]
Submitted PR, I surrender - I'm noob when it comes to these new CMake configs with targets etc. - I have no idea on how to make it consistent name-wise and work with as much of original CMakeLists as possible.. 

So far it compiles but then errors on this:
```
-- [hunter *** DEBUG *** 2019-04-22T19:02:46] load: D:/Projects/hunter/_testing/Hunter/_Base/Download/Hunter/unknown/58ca831/Unpacked/cmake/projects/AngelScript/hunter.cmake ... end
CMake Warning (dev) at CMakeLists.txt:13 (find_package):
  Policy CMP0074 is not set: find_package uses <PackageName>_ROOT variables.
  Run "cmake --help-policy CMP0074" for policy details.  Use the cmake_policy
  command to set the policy and suppress this warning.

  Environment variable AngelScript_ROOT is set to:

    D:/Projects/hunter/_testing/Hunter/_Base/58ca831/7baeb72/ba32050/Install

  For compatibility, CMake is ignoring the variable.
This warning is for project developers.  Use -Wno-dev to suppress it.

CMake Error at CMakeLists.txt:13 (find_package):
  Could not find a package configuration file provided by "AngelScript" with
  any of the following names:

    AngelScriptConfig.cmake
    angelscript-config.cmake

  Add the installation prefix of "AngelScript" to CMAKE_PREFIX_PATH or set
  "AngelScript_DIR" to a directory containing one of the above files.  If
  "AngelScript" provides a separate development package or SDK, be sure it
  has been installed.
```

**Comment by noizex** [comment]
Ok may be that configure_package_config_file did not install the file - I only see 
![image](https://user-images.githubusercontent.com/3256633/56513244-20870300-6532-11e9-827e-4357b1a6f15d.png)

**Comment by ruslo** [comment]
>I'm noob when it comes to these new CMake configs with targets etc.

Few links here might be helpful:
- https://docs.hunter.sh/en/latest/creating-new/create/cmake.html#install-xxxconfig-cmake

It's a core of Hunter, without this feature nothing will work :)

**Comment by noizex** [comment]
Ok, I will have a look. Right now I have no idea why the main Config file is not installed:
```
configure_package_config_file(
  "cmake/Config.cmake.in"
  "AngelScriptConfig.cmake"
  INSTALL_DESTINATION ${ConfigPackageLocation}
 )
```

I tried adding another install() command but nothing works. I'll try to read on it as I tried guessing and hoping it will work but I need more understanding here...

**Comment by ruslo** [comment]
Please work on CMake improvements with upstream developers.

**Comment by noizex** [comment]
I'll just use Conan for now, thanks for your time.
